# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a69bcc218cf2c54769384e65b6ba960d081d0bb589aee990ee6ac42ea155564df2a5e2b13acd21c9c0a98eb1bdc0a36bd0735b414c4c7bfba766bf95349b2f3d

test:
  secret_key_base: 07d9324b5f274296ba9929f68394563433b3c0c1d508c1bcfc925b9f5bec5489e7db33f1d2106e07949e8771c4c2d2a354cf17550034e3a26357f8318858faa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
